---
title: "Proposed Approach for Developing Wildlife Factors for Timber Supply Reviews"
author: "Tyler Muhly"
date: "25/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Wildlife and Timber Supply Reviews
Here I propose a standard approach for developing wildlife-specific 'factors' for timber supply reviews (TSRs). There is a need to effectively consider wildlife in TSRs and account for the effects of allowable annual cut (AAC) decisions on wildlife. In particular, recent court decisions in British Columbia (BC) have stated that statutory decision makers must use credible information to consider the effects of land management decisions, including AAC determinations, on Indigenous peoples rights to harvest wildlife (e.g., see [William v. British Columbia 2012](https://www.bccourts.ca/jdb-txt/CA/12/02/2012BCCA0285.htm) and [West Moberly First Nations v. British 2011](https://www.bccourts.ca/jdb-txt/CA/11/02/2011BCCA0247.htm)). Accommodations to First Nations communities for impacts of forest harvest on wildlife may be necessary as part of some AAC decisions. The approach described here is intended to support the creation of 'credible' information on the status of valued wildlife species in a TSA for the Chief Forester to consider as part of AAC determinations. 

## Collaboration on Wildlife Analyses to Support Timber Supply Reviews
The standard approach described here is useful as a starting point for developing information on wildlife for TSR's. However, wildlife analyses to support the TSR process should be flexible, and deviations from this approach are encoruraged where they promote better information to support AAC determinations. In particular, the approach should be modified where necessary to enhance collaboration with First Nations and increase their trust in the information. Ultimately, wildlife analyses should, wherever possible, be developed in collaboration with First Nations. 

In addition, where possible I recommend that wildlife analyses are completed under advisement of regional wildlife biologists. They will be able to provide important context on the information, and to make recommendations on how to adjust these analyses so they are more appropriate to the local ecological conditions. For example, moose may respond to forestry activity differently across different regions beacuse of unique habitat conditions or animal behaviours. In addition, local biologists will likely have important insights on how forestry activity could be modified to improve habitat conditions for wildlife species of interest. Thus, they can provide advice on alternative management regimes that could be implemented as scenarios in timber supply models to assess their potential impact to timber supply. 

## Wildlife Templates for Timber Supply Reviews
I provide standard templates for developing wildlife factors to support AAC determinations. I provide these templates as R markdown files (.rmd's) that document text and, where possible, functioning code to manipulate, analyze and visualize data. The templates do not necesarily have to be applied to every TSR process. They are not intended to be applied as strict and inflexible standards. Other approaches may be developed for a specific TSR if they are more appropriate, and in particular, if they are favoured by First Nations communities that are partnering in TSR processes. However, the templates are useful in the absence of those partnerships and to provide a starting point for developing wildlife factors for AAC determinations. 

The templates include seven sections:
1. Importance of the Wildlife Species in the Timber Supply Area
2. Key Relationships Between the Wildlife Species and Forestry 
3. Forestry-related Indicators of the Wildlife Species' Habitat and Population Conditions
4. Current State of the Wildlife Species' Habitat and Populations in the Timber Supply Area
5. The Wildlife Species' Habitat and Population Management Tools
6. Simulated Future States of the Wildlife Species Habitat and Populations Under Different Management Scenarios in the Timber Supply Area 
7. Conclusions

The intent of these sections are to descibe why the wildife species of interest is important in a timber supply area (TSA), how that species relates to forestry, the current status of the species in the TSA, management options for that species (relevant to forestry and the TSA), simulated future status of the species under alternative forest management regimes and conclusions about the current and potential future impacts of forestry on the wildlife species.  

## Limitations Around Wildlife Indicators in Timber Supply Reviews
Prior to discussing which wildlife values to include in TSR, it is important to understand some of the limitations around timber supply models and how they can be used to assess future conditions of wildlife habitat and populations. 

Wildlife habitat indicators should be estimated using commonly available data that can be integrated with TSR. Thus, [vegetation resources inventory data](https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-rank-1-layer-r1-), and roads data from the [digital road atlas (DRA)](https://catalogue.data.gov.bc.ca/dataset/digital-road-atlas-dra-master-partially-attributed-roads) and [forest tenure roads](https://catalogue.data.gov.bc.ca/dataset/243c94a1-f275-41dc-bc37-91d8a2b26e10) are likely going to be important datasets. These datasets can be used to calculate current habitat conditions, but estimating future conditions will be reliant on outputs from timber supply models. 

The two outputs from timber supply models that are likely going to be most relevant to wildlife habitat are forest stand characteristics and roads. TSR models rely on estimates of forest stand characteristics from tree or forest stand growth and yield models, specifcially, the variable density yield projection [VDYP](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/growth-and-yield-modelling/variable-density-yield-projection-vdyp) model for natural origin stands and the [table interpolation program for stand yields (TIPSY)](https://www2.gov.bc.ca/gov/content/industry/forestry/managing-our-forest-resources/forest-inventory/growth-and-yield-modelling/table-interpolation-program-for-stand-yields-tipsy) model for managed stands. VDYP can output stand age, volume, height and basal area estimates. TIPSY uses inputs from the tree and stand simulator (TASS) model, which estimates a wider variety of stand characteristics than VDYP, for example, crown closure development and understory light levels. Wildlife habitat and population models that can be linked to these characteristics will be most powerful for simulating potential impacts of future forestry on wildlife. 

All TSR models can provide outputs on forest stand age, as they all track annual time steps and when a stand is harvested. Wildlife indicators related to stand age are therefore realtively simple to integrate with timber supply models, and this has been done in the past (e.g., in the [Prince George TSA](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/tsr-annual-allowable-cut/wildlife-analysis/pg_tsr_caribou_20161128.pdf) and [Cranbrook, Invermere and Arrow TSAs](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/tsr-annual-allowable-cut/wildlife-analysis/kootenaytsas_habitat_supply_summary_final_20160914.pdf)). However, there is an opportunity to incorporate other stand-level information (e.g., height and canopy closure) that can be linked to forest stand models into habitat models. Opportunities to include these details should be explored early in the development of timber supply models so that these other indicators can be produced from growth and yield models and estimated across TSA's. 

Some timber supply models spatially simulate future roads, by connecting simulated future cutblocks to existing road networks. Thus, outputs from these models can be used to estimate future road indicators for wildlife. However, for models that do not simulate future roads, road densities can be estimated from cutblock densities at a landscape unit or watershed scale using a [statistical model](https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/forestry/stewardship/forest-analysis-inventory/tsr-annual-allowable-cut/wildlife-analysis/road_cutblock_model_20161102.pdf). 

Another important consideration is that timber supply models are not necessarily designed to accurately simulate the location and timing of future forest harvest areas. Therefore, the spatial and temporal configuration of forest harvest outputs from timber supply models should be used with caution. It is likely that the more generalizable that model outputs are made spatially and temporally, the more useful the model outptus will be. For example, I recommend at a minimum summarizing forest stand and road attributes at the landscape unit or watershed assessment area scales, over 10 or 20 year periods.  

## Wildlife Species of Relevance to Timber Supply Reviews
I developed standard templates for wildlife species that are likely to be of high management or conservation priority across TSAs, and that have a clear connection to forestry development. The value of a particular wildlife species to First Nations and other communities can vary across BC. However, there are some species that cover large extents of BC and are generally highly valued across the province for conservation or socio-economic reasons. Another important consideration is the connection between the wildlife species and forestry. Obviously, AAC decisons are specific to forestry, and therefore, when considering the effects of the decison on wildlife, the focus should be on species that are clearly and strongly influenced by forestry. Based on these two criteria, I have identified three species to consider as part of TSRs. These include:
- Moose (*Alces alces*)
- Grizzly bear (*Ursus arctos horribilis*)
- Fisher (*Pekania pennanti*)

These three species have ranges that cover large extents of BC and they all appear to be strongly influenced by forestry. The list may expand or change in the future, but for now these three species are a useful starting point for considaration in TSRs. Below I provide a more detailed rational for including each of these species in TSRs, which could be used to help develop a factor for these species in an AAC determination. A standard template for each of these species to support development of a TSR factor is also included in this folder. 

### Moose
Moose are widely distributed across the majority of BC, and are particularly abundant in the central interior and northern boreal mountains ( [Moose In British Columbia](http://www.env.gov.bc.ca/wld/documents/moose.pdf)). They are typically a highly valued wildlife species in North America for a variety of cultural and economic reasons ( [Timmermann and Rogers 2005](https://pdfs.semanticscholar.org/55d2/86e83dd7cae6da270c153858b3d1a98d89de.pdf)). 

Prior to European colonization, moose were used extensively by Indigenous peoples for food, clothing and shelter ( [Moose In British Columbia](http://www.env.gov.bc.ca/wld/documents/moose.pdf)). In the last 100 years, moose have become an important, nutritious, staple food of many interior and coastal First Nations communities in BC ( [First Nations Health Authority fact sheet](https://www.fnha.ca/Documents/Traditional_Food_Fact_Sheets.pdf)). First Nations have taken leadership roles in moose management in BC, for example, partnering with the government of BC to co-manage moose in the Chilcotin region, where moose population declines were of concern ( [Vancouver Sun 2018](https://vancouversun.com/news/local-news/b-c-government-and-first-nation-sign-deal-to-manage-declining-moose-populations/). Moose are currently a culturally important species to many First Nations, for example, moose are a key symbol in a First Nations led campaign to end domestic violence in Canada ( [Moose Hide Campaign](https://moosehidecampaign.ca/home/about-us)).

Moose are a key game species in BC, for sustenance and as a trophy species ( [Moose In British Columbia](http://www.env.gov.bc.ca/wld/documents/moose.pdf)). Annually, approximately 40,000 moose hunting licenses are sold in BC, with typically over 250,000 days spent moose hunting ( [Kuzyk 2016](https://alcesjournal.org/index.php/alces/article/download/155/199)). However, while these numbers are relatively stable, the number of succesfull hunts has been declining in the last 15 years, to approximately 6,000 licensed moose harvested annually across BC ( [Kuzyk 2016](https://alcesjournal.org/index.php/alces/article/download/155/199)). Moose also have significant non-consumptive value, as part of ecotourism and wildlife viewing ( [Moose In British Columbia](http://www.env.gov.bc.ca/wld/documents/moose.pdf)). 

There is evidence of recent declining moose populations in many parts of BC. Moose population declines of approximately 20-40% occurred in the Omineca and Cariboo regions of British Columbia from 2008 to 2014 ( [Kuzyk 2016](https://alcesjournal.org/alces/index.php/alces/article/download/155/199)). More specifically, moose were declining in 25% of game management zones (GMZs) in BC from 1996 to 2005 and in 71% of GMZs from 2006-2015 ( [Kuzyk et al. 2018](http://alcesjournal.org/index.php/alces/article/download/240/274)). These declines triggered the implementation of a large research program in central BC to study causes of moose mortality ( [Kuzyk and Heard 2014](https://www2.gov.bc.ca/assets/gov/environment/plants-animals-and-ecosystems/wildlife-wildlife-habitat/wildlife-health/wildlife-health-documents/2014_bc_moose_research_design.pdf); [Kuzyk 2016](https://alcesjournal.org/alces/index.php/alces/article/download/155/199)).

#### Relationship to Forestry
Research has shown that forestry activity influences moose density and distribution, both positively and negatively. Moose require a mix of forest cover types within their home ranges, and deciduous shrub and tree browse is a key forage element ( [Crete 1988](https://pubs.cif-ifc.org/doi/pdfplus/10.5558/tfc64246-3)), including species such as *Salix spp.*, *Populus tremuloides*, *Betula papyrifera*, *Corylus cornuta*, *Prunus pensylvanica*, *Amelanchier alnifolia* and *Cornus spp.* ( [Peek et al. 1976](https://www.jstor.org/stable/3830485?seq=1); [McNicol and Gilbert 1980](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/3807966.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A1f887ac9dfbe73bc019bed2593bcf800); [Poole and Stuart-Smith 2005](https://www.researchgate.net/profile/Kim_Poole/publication/259568012_FINE-SCALE_WINTER_HABITAT_SELECTION_BY_MOOSE_IN_INTERIOR_MONTANE_FORESTS/links/0c96052c8f313bbc3a000000/FINE-SCALE-WINTER-HABITAT-SELECTION-BY-MOOSE-IN-INTERIOR-MONTANE-FORESTS.pdf)). Forestry cutblocks remove forest canopy, which generally increases the production of deciduous shrub browse on landscapes, which can positively influence moose ( [Crete 1988](https://pubs.cif-ifc.org/doi/pdfplus/10.5558/tfc64246-3); [Leclerc et al. 2012](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322)). Thus, the potential positive effects of forestry on moose are related to the creation of early seral forest habitat, which favours the production of moose forage on a landscape. 

In general, the benefits of a forest cutblock to moose follows the succesional pattern of stand recovery. New cutblocks (less than 5 years old) may be of little use to moose ( [Eastman 1977](https://open.library.ubc.ca/cIRcle/collections/ubctheses/831/items/1.0094631)), likely because it takes shrubs a few years to occupy and grow in a harvested area. Shrub production in forestry cutblocks varies, but appears to peak anywhere from at 5 to 30 years after harvest, and moose appear to use these stand types the most ( [Peek et al. 1976](https://www.jstor.org/stable/3830485?seq=1); [Crete 1977](https://www.nrcresearchpress.com/doi/pdf/10.1139/x77-034); [Eastman 1977](https://open.library.ubc.ca/cIRcle/collections/ubctheses/831/items/1.0094631); [Crete 1988](https://pubs.cif-ifc.org/doi/pdfplus/10.5558/tfc64246-3); [Leclerc et al. 2012](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322)). Cutblocks older than 30 years old (i.e., mid-seral stands), appear to generally be of less forage value to moose ( [Peek et al. 1976](https://www.jstor.org/stable/3830485?seq=1); [Leclerc et al. 2012](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322)) and thus receive less use ( [Schneideman 2018](http://web.unbc.ca/~michael/Pubs/Matt%20Scheideman%20Thesis%20Final%20for%20distribution.pdf)). 

The positive effects of cutblocks on moose forage may not be universal. For example, they can be diminished or lost when conifers are planted at high densities, or shrub thinning or herbicides are applied to limit the growth of deciduous vegetation within cutblocks ( [Peek et al. 1976](https://www.jstor.org/stable/3830485?seq=1); (https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322)). In contrast, reducing the density of conifer plantations can benefit moose by promoting shrub growth. For example, thinning of lodgepole pine forests in the Penticton, Prince George and Kamloops areas of BC to approximately 500 stems/ha resulted in higher shrub volume and moose use in cutblocks compared to old stands, unthinned cutblocks or stands thinned at higher densities, i.e., 1,000 to 2,000 stems/ha  ( [Sullivan et al. 2007](https://appliedmammal.com/content/publications/FEM%20240%2032-41%202007.pdf). However, recent reaserch in central BC, found that at large scales (over a period of 180 days to a year), moose were more likely starve to death in areas with higher road and cutblock densites ( [Mumma and Gillingham 2019](http://web.unbc.ca/~michael/Mumma_and_Gillingham_2019.pdf)), suggesting that the characteristics of forest harvest in those areas is providing no forage benefit to moose. Indeed, recent work south of Prince George has indicated that shrubs in open areas of large cutblocks may provide limited protein value for moose, especially compared to shrubs along cutblock edges and in adjacent mature and old forest ( [J. Werner, FLNRORD Wildlife Biolgoist, pers. comm.](https://video.unbc.ca/media/The+abundance+of+scarcityA+landscape+change%2C+protein+limitation%2C+and+moose+population+dynamics+in+north-central+BC.+Dr.+kJeff+Werner%2C+BC+Ministry+of+Forests%2C+Lands%2C+Natural+Resource+Operations%2C+and+Rural+Development+-+October+18+2019/0_pbu2wpdw/19801)). Thus, not all cutblocks will be of equal forage value to moose, and how vegetation is managed in cutblocks plays a key role in determining that value.    
Older stands, including mature cutblocks, can also benefit moose by providing valuable cover habitat. Closed canpoy conifer forest is important habitat for providing thermal cover in summer and to intercept snow in high snowfall years or areas ( [Eastman 1977](https://open.library.ubc.ca/cIRcle/collections/ubctheses/831/items/1.0094631); [Schwab 1985](https://open.library.ubc.ca/cIRcle/collections/ubctheses/831/items/1.0097322#downloadfiles); [Crete 1988](https://pubs.cif-ifc.org/doi/pdfplus/10.5558/tfc64246-3); [Demarchi and Bunnell 1995](https://www.researchgate.net/profile/Fred_Bunnell/publication/279886949_Forest_cover_selection_and_activity_of_cow_moose_in_summer/links/59f656bb0f7e9b553ebd29ab/Forest-cover-selection-and-activity-of-cow-moose-in-summer.pdf)). 

Ultimately, a diversity of forest stand types is necessary to provide good habitat for moose ( [Eastman 1977](https://open.library.ubc.ca/cIRcle/collections/ubctheses/831/items/1.0094631); [Schwab 1985](https://open.library.ubc.ca/cIRcle/collections/ubctheses/831/items/1.0097322#downloadfiles)), and configuration of those stands is also important. Aggregation of uniform forest types will result in poor moose habitat. For example, [Leclerc et al. (2012)](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322) found that increasing aggregation of 15-30 year old harvested stands resulted in lower use of those areas by moose. Similarly, leaving large uncut areas adjacent to cutblocks (i.e., 'leave blocks') was found to be positively related to moose density ( [Eason 1989](http://flash.lakeheadu.ca/~arodgers/Alces/Vol25/Alces25_63.pdf)). To achieve a diversity of forest types, limits on cutblock size have been proposed and applied as part of moose management. For example, [Peek et al. (1976)](https://www.jstor.org/stable/3830485?seq=1) proposed that cutblocks less than 80 ha in size were ideal for moose. However, [Rempel et al. (1997)](https://www.jstor.org/stable/3802610?seq=1) found that a provincial moose habitat policy to maintain cutblock sizes less than 130 ha in Ontario did not result in higher moose densities. Landscapes with an intermediate level of forest harvest appear to be favoured by moose ( [Schneideman 2018](http://web.unbc.ca/~michael/Pubs/Matt%20Scheideman%20Thesis%20Final%20for%20distribution.pdf)), and [Poole and Stuart-Smith (2006)](https://www.researchgate.net/profile/Kim_Poole/publication/237973775_Winter_habitat_selection_by_female_moose_in_western_interior_montane_forests/links/0046351ef1db0e19df000000.pdf) recommended a configuration of 40-45% forage and 20-25% cover habitat to provide high quality winter habitat for moose. 

Forest harvest, when done in moderation and in a way that creates a complex configuration of forest stands, can potentially benefit moose. However, the creation of road infrastrucutre to extract timber could negate those benefits and in some cases negatively affect moose density and distribution overall ( [Leclerc et al. 2012](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322)). Forestry roads can make areas more accessible to moose hunters, increasing hunting mortality, which can limit moose population size ( [Eason 1989](http://flash.lakeheadu.ca/~arodgers/Alces/Vol25/Alces25_63.pdf)). [Rempel et al. (1997)](https://www.jstor.org/stable/3802610?seq=1) found that modified harvest practices to create smaller cutblocks resulted in lower moose densities due to the higher associated road densities in those areas. Recent research in central BC found that moose avoided roads, particularly in highly roaded areas ( [Schneideman 2018](http://web.unbc.ca/~michael/Pubs/Matt%20Scheideman%20Thesis%20Final%20for%20distribution.pdf)). In addition, at a fine scale (over a period of a day to a week), moose were more likely to be killed by hunters when moving in areas with higher road densities and new cutblocks ( [Mumma and Gillingham 2019](http://web.unbc.ca/~michael/Mumma_and_Gillingham_2019.pdf)). A combination of newly open cutblocks accessible by road may be especially poor habitat for moose ( [Rempel et al. 1997](https://www.jstor.org/stable/3802610?seq=1)), as moose are likely highly vulnerable to hunters there due to a combination of accesibility and open site lines. 
Moose were found to much less frequently cross roads in areas with road densities of 0.2 km/km^2^ in summer and 0.4 km/km^2^ in winter ( [Beyer et al. 2013](https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/1365-2664.12042)). Similarly, [Frair et al. (2008)](https://besjournals.onlinelibrary.wiley.com/doi/pdf/10.1111/j.1365-2664.2008.01526.x) found that elk (*Cervus elaphus*) avoided and were less likely to survive in areas with road densities greater than 0.25 to 0.5 km/km^2^. [Forman et al. (1997)](http://www.lauxen.net/conecte/referencias/Forman_1997a.pdf) suggested that in general, large mammal populations decline once a threshold desnity of 0.6 km/km^2^ roads is surpassed. The overall effects of forestry on moose may be negative when roads endure on the landscape and are not actively decommissioned or recovered ( [Leclerc et al. 2012](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/23361352.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322)).     

Moose have an important and complex relationship with forestry development. Based on a review of previous research on the effects of forestry on moose, the relationship is most likely to be positive when:
- At the scale of a moose home range (i.e., approximately 10 km^2^), forest cutblocks are cut in a progressive way over a 5 to 10 year period, and interspersed with large mature or old forest stands, so there is a distribution of cutblock ages 
- Silvicultural practices on harvested stands allow for growth of some shrubs, particularly along edges with old forest stands   
- Roads are minimized, blocked, deactivated and restored

#### Indicators of Habitat and Populations
Within the context of the key moose-forestry relationships identified above, there are some potential moose habitat indicators or constraints that could be implemented as part of TSR models, including: 

- indicators, or constraints on the area of early, mid and late seral stage forest stands within a watershed or landscape unit
  
  - for example, a distribution of 40% five to 30 year old cutblocks and 20% old forest with dense canpopy closure may be ideal targets for a landscape unit or watershed 

- indicators, or constraints on road density

  - for example, a threshold of 0.6 km/km^2^ within a landscape unit or watershed 

- cutblock replanting stocking targets

  - for example, implementation of low density conifer stocking (500 stems/ha) in areas where moose forage production is a priority 

In addition to habitat indicators, it will be useful to consider some moose population indicators to provide context on moose population status and trend within a TSA. Where available, moose population trend estimates should be used. These are typically estimated using [aerial survey methods](https://www2.gov.bc.ca/assets/gov/environment/natural-resource-stewardship/nr-laws-policy/risc/unga_ml20_final.pdf) within [wildlife managment units (WMUs)](https://catalogue.data.gov.bc.ca/dataset/wildlife-management-units). However, these data are not likely to be available across all WMUs within a TSA, and may not be recent. Thus, these data will likely provide an incomplete picture on moose population status and trend across a TSA over time. Other indicators, such as bull:cow and calf:cow ratios estimated from aerial surveys may also be used to indicate population stability or trend ( [Young and Boertje 2008](https://alcesjournal.org/index.php/alces/article/view/37); [Walker et al. 2017](http://a100.gov.bc.ca/pub/siwe/download.do?docId=34052); [FLNRORD 2019](http://www.env.gov.bc.ca/fw/wildlife/management-issues/docs/2019%20Moose%20Factsheet.pdf)). 

Moose population data can be searched for using the [species inventory web explorer (SIWE)](http://a100.gov.bc.ca/pub/siwe/search_reset.do) and the [wildlife species inventory (SPI) data](https://catalogue.data.gov.bc.ca/dataset/wildlife-species-inventory-results-by-area-all). In the absence of density data, kill per unit effort (KPUE) may be used as an index of population density, particulalry where there is more road access [Kuzyk et al. 2018](http://alcesjournal.org/index.php/alces/article/download/240/274). 

Moose use of habitat varies depending on animal behaviours and local habitat context ( [Eastman 1974](https://www.arlis.org/docs/vol2/hydropower/APA_DOC_no._1065.pdf); [Osko et al. 2004](https://www-jstor-org.ezproxy.library.ubc.ca/stable/pdf/3803391.pdf?ab_segments=0%2Fbasic_SYC-5055%2Ftest&refreqid=search%3A80dbc9cab1a0c6625f7492d10d952322); [Gillingham and Parker 2008](https://alcesjournal.org/alces/index.php/alces/article/download/33/32)). Thus, general indicators and constraints should be used with caution. I recommend discussing these indicators with regional and district government wildlife biolgists to customise them so they are appropriate to the local context.

#### Calculation of Indicators for Timber Supply Reviews
Once appropriate indicators have been determined, they can be used to estimate the current state of moose populations and habitat in a TSA. I recommend calculating indicators at the scale of a [landscape unit (LU)](https://catalogue.data.gov.bc.ca/dataset/landscape-units-of-british-columbia-current) or [freshwater assessment watershed area (AWA)](https://catalogue.data.gov.bc.ca/dataset/freshwater-atlas-assessment-watersheds). I also recommend summarizing moose population  data, where available, at the WMU scale. 

#### Management Tools and Constraints
Information on the current state of moose populations and habitat is useful, and could be sufficient for an AAC determination discussion. However, it may also be valuable to assess potential future habitat conditions under alternative forest management scenarios. Habitat indicators may be estimated in the future under a 'base case' timber supply scenario to assess how timber harvest might influence moose in the future. For example, road and stand age outputs from TSR models could be used to update these indicators over time. This provides an assessment of how forestry under current legislated constraints might influence moose habitat in the future, and whether that is of concern. 

If possible (and necessary), future conditions under the base case could be compared to alternative management scenarios designed to improve moose population and habitat sustainability. This can potentially provide valuable information on how management scenarios designed for moose influence timber supply, and thus how changes to AAC might influence moose habitat and populations. However, it is important to note that a reduction in AAC would not necessarily benefit a species such as moose. These reductions would likely have to be done in combination with more specific direction on how forest harvest is conducted. Alternative management scenarios for moose could include applying new constraints (i.e., limits) on road density and forest age classes, and silvicultural prescriptions to specified areas where moose habitat improvements are deemed valuable or necessary. These areas could be LU's or AWA's identified as important for maintaining high moose densities.   






### Grizzly Bear
Grizzly bear are a focal wildlife management species in Canada and British Columbia because of their social, cultural and conservation value. Grizzly bear viewing and hunting are important economic and social components of British Columbia’s tourism and recreation industries [Environmental Reporting BC 2012](http://www.env.gov.bc.ca/soe/indicators/plants-and-animals/grizzly-bears.html).




The Committee on the Status of Endangered Wildlife in Canada lists them as species of [*Special Concern*](https://www.sararegistry.gc.ca/virtual_sara/files/cosewic/sr_ours_grizz_bear_1012_e.pdf) due to their high sensitivity to human-caused disturbance and mortality where roads facilitate access and human-bear interactions.	In British Columbia, they are blue listed (i.e., species of special concern because of characteristics that make them particularly sensitive to human activities or natural events) and have a S3 conservation status (i.e., rare and local, found only in a restricted range or susceptible to extirpation or extinction).




Grizzly bear are wide ranging species that use a variety of habitats for food and shelter. They are therefore influenced broadly, at large scales and by a variety of land uses. They are sometimes considered as “umbrella” or “indicator” species, meaning the status of their populations may be indicative of the status of other wildlife species or environmental values where they live.




### Fisher

https://www.bcfisherhabitat.ca/fisher-ecology/



## Engagement with First Nations
Ideally, the determination of priority wildlife species for assessment as part of TSRs should be done in collabortion with First Nations communities in the TSA or affected by the TSR decision. The information above can be used as a starting point to help inform that discussion. However, in practice, consultation and collaboration with First Nations may be challenging for a variety of reasons, in particular because it depends on the type of existing relationship between First Nations governments and the provincal government. Where those relationships are generally productive, it may be possible to link into existing discussions and with regional staff to set-up mechanisms for discussing TSR and infringment on rights. However, where those relationships are poor, it may be impossible to initiate those discussions, in which case the standard factors may be used. 

Consultation with First Nations will be conducted as part of the TSR process, and consultation related to wildlife analyses and infringement of rights shoudl happen as part of that process. Thus, a key to htis analysis is close communication with the consultation team involved in each TSR. All consulation and collaboration with First Nations should be documented for the determination factor.  







