---
title: "Proposed Moose Factor Template"
author: "Tyler Muhly"
date: "25/05/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. Importance of Moose in the Timber Supply Area
Within this section:

- provide some context on why moose are being highlighted for the allowable annual cut (AAC) determination, for example:

  - use some of the high-level information provided in the 00_widlife_README.rmd

  - provide any local context on the importance of moose, for example, provide information on any initiatives to enhance moose habitat in the TSA

  - in particular, and most important, if information is available, emphasize why moose are important to First Nations communities in the TSA

## 2. Key Relationships Between Moose and Forestry   
Within this section:

- summarize some of the high-level information provided in the 00_widlife_README.rmd that describes the relationship between moose and forestry

- where possible, add local context on moose-forestry relationships, for example, results of research on moose and forestry relationships conducted in or near the TSA

- where available and permitted to do so, include a summary of any First Nations knowledge and data on moose 

## 3. Forestry-related Indicators of Moose Habitat and Populations
Within this section:

- identify and explain the habitat and population indicators used in the analysis and why they are important to moose management

  - habitat indicators related to forest age, ratios of old and young, or open and closed forest stands, and road density may be appropriate

  - spatial habitat data can be downloaded from [DataBC](https://data.gov.bc.ca/), for example, the [digital road atlas (DRA)](https://catalogue.data.gov.bc.ca/dataset/digital-road-atlas-dra-master-partially-attributed-roads), [forest tenure (FTEN) roads](https://catalogue.data.gov.bc.ca/dataset/forest-tenure-road-segment-lines), and [forest vegetation resources inventory (VRI)](https://catalogue.data.gov.bc.ca/dataset/vri-2019-forest-vegetation-composite-rank-1-layer-r1-)

- where available, provide moose population trend and density information, and bull:cow and calf:cow ratios across the TSA

  - bull:cow and calf:cow ratios are considered indicators of healthy moose populations, where ratios greater than 30 indicate populations that are not over-hunted, and stable or increasing, respectively 
  
  - population data may be found using the [species inventory web explorer (SIWE)](https://catalogue.data.gov.bc.ca/dataset/species-inventory-web-explorer-siwe)

## 4. Current State of Moose Habitat and Populations in the Timber Supply Area
Within this section:

- summarize and visualize indicators of moose habitat and populations, including, for example:

  - maps of current moose density or kills per unit effort (KPUE) at the wildlife management unit (WMU) scale
  
  - trend in moose density or KPUE in the region where the TSA occurs
  
  - maps of current road density across the TSA at landscape unit (LU) or freshwater assessment watershed area (AWA) scales
  
  - frequency distribution or box plot showing distribution of road density across LU's or AWA's 
  
  - maps of proportion of young (e.g., 0 to 30 year old) forest stands across the TSA at LU or AWA scales 
  
  - frequency distribution or box plot showing distribtuion of young forest stands across LU's or AWA's
  
  - maps of proportion of older (e.g., greater than 80 year old) and/or closed canopy conifer forest stand across the TSA at LU or AWA scales 
  
  - frequency distribution or box plot showing distribtuion of older and/or closed canopy conifer forest stands across LU's or AWA's
  
- the above are suggestions; these can be modified, or alternatives can be used based on local knowledge or needs

- where available, use summaries and visualizations of these indicators to show thresholds, limits or risks to moose habitat and populations  

- in addition, summarize and visualize any First Nations knowledge and data, where available and permitted to do so

## 5. Moose Habitat and Population Management Tools 
Within this section:

- describe any moose management tools that could be applied in the TSA (in addition to what has and is already being done)

- where relevant, describe any moose management scenarios applied in the TSR model to compare to the base case 
  
  - describe how the scenario(s) was applied in the TSR model (e.g., new constraints on timber harvest)

## 6. Simulated Future States of Moose Habitat and Populations Under Different Management Scenarios in the Timber Supply Area 
Within this section:

- summarize and visualize simulated future indicators of moose habitat under base case and (where available) alternative moose management scenarios, for example: 
  
  - maps of simulated future road density across the TSA, at LU or AWA scales, at future time intervals
  
  - frequency distribution or box plot showing distribution of simulated road density across LU's or AWA's, at future time intervals
  
  - maps of proportion of simulated future young forest stands across the TSA at LU or AWA scales, at future time intervals
  
  - frequency distribution or box plot showing distribution of simulated future young forest stands across LU's or AWA's, at future time intervals
  
  - maps of proportion of simulated future old forest stands across the TSA at LU or AWA scales, at future time intervals
  
- summarize and visualize simulated future AAC of moose management scenario(s) (where available) compared to the base case
  
## 7. Conclusions
Within this section:

- provide a general overview of current and potential future population and habitat conditions for moose

- describe whether current indicators of moose population or habitat suggest there are existing risks to moose population sustainability in the TSA 
  
- highlight any potential future risks to moose habitat and populations under future simulated forest harvest under the base case, or alternative scenarios
  
- discuss potential timber supply impacts of alternative moose management scenarios, and potential trade-offs between moose sustainability and timber supply 
